config/routes.rb
Rails.application.routes.draw do
  resources :sandwiches

  sitepress_pages
  sitepress_root
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/sandwich.rb
class Sandwich < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sandwiches_controller.rb
class SandwichesController < ApplicationController
  before_action :set_sandwich, only: %i[ show edit update destroy ]

  # GET /sandwiches or /sandwiches.json
  def index
    @sandwiches = Sandwich.all
  end

  # GET /sandwiches/1 or /sandwiches/1.json
  def show
  end

  # GET /sandwiches/new
  def new
    @sandwich = Sandwich.new
  end

  # GET /sandwiches/1/edit
  def edit
  end

  # POST /sandwiches or /sandwiches.json
  def create
    @sandwich = Sandwich.new(sandwich_params)

    respond_to do |format|
      if @sandwich.save
        format.html { redirect_to sandwich_url(@sandwich), notice: "Sandwich was successfully created." }
        format.json { render :show, status: :created, location: @sandwich }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sandwich.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sandwiches/1 or /sandwiches/1.json
  def update
    respond_to do |format|
      if @sandwich.update(sandwich_params)
        format.html { redirect_to sandwich_url(@sandwich), notice: "Sandwich was successfully updated." }
        format.json { render :show, status: :ok, location: @sandwich }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sandwich.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sandwiches/1 or /sandwiches/1.json
  def destroy
    @sandwich.destroy

    respond_to do |format|
      format.html { redirect_to sandwiches_url, notice: "Sandwich was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sandwich
      @sandwich = Sandwich.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sandwich_params
      params.require(:sandwich).permit(:name, :category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sandwiches_helper.rb
module SandwichesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fly Rails Playground</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <main class="container mx-auto p-12 flex flex-col gap-y-12">
      <%= yield %>
    </main>
  </body>

</html>

app/views/layouts/page.html.erb
<%= render_layout "application" do %>
  <header class="flex flex-row items-center justify-center gap-x-8 py-12">
    <%= image_tag "brandmark.svg", class: "max-w-[6rem]" %>
    <h1 class="font-bold text-4xl"><%= current_page.data.fetch("title") %></h1>
  </header>
  <article class="prose max-w-none">
    <%= yield %>
  </article>
<% end %>

app/views/sandwiches/_form.html.erb
<%= form_with(model: sandwich, class: "contents") do |form| %>
  <% if sandwich.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(sandwich.errors.count, "error") %> prohibited this sandwich from being saved:</h2>

      <ul>
        <% sandwich.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :category %>
    <%= form.text_field :category, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/sandwiches/_sandwich.html.erb
<div id="<%= dom_id sandwich %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= sandwich.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Category:</strong>
    <%= sandwich.category %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this sandwich", sandwich, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this sandwich', edit_sandwich_path(sandwich), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/sandwiches/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing sandwich</h1>

  <%= render "form", sandwich: @sandwich %>

  <%= link_to "Show this sandwich", @sandwich, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to sandwiches", sandwiches_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/sandwiches/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Sandwiches</h1>
    <%= link_to 'New sandwich', new_sandwich_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="sandwiches" class="min-w-full">
    <%= render @sandwiches %>
  </div>
</div>

app/views/sandwiches/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New sandwich</h1>

  <%= render "form", sandwich: @sandwich %>

  <%= link_to 'Back to sandwiches', sandwiches_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/sandwiches/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @sandwich %>

    <%= link_to 'Edit this sandwich', edit_sandwich_path(@sandwich), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this sandwich', sandwich_path(@sandwich), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to sandwiches', sandwiches_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>